from sqlalchemy import Column, Integer, String, Float
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Fire(Base):
    __tablename__ = "fires"
    objectid = Column(Integer)
    fod_id = Column(Integer, primary_key=True)
    fpa_id = Column(String)
    source_system_type = Column(String)
    source_system = Column(String)
    nwcg_reporting_agency = Column(String)
    nwcg_reporting_unit_id = Column(String)
    nwcg_reporting_unit_name = Column(String)
    source_reporting_unit = Column(String)
    source_reporting_unit_name = Column(String)
    local_fire_report_id = Column(String)
    local_incident_id = Column(String)
    fire_code = Column(String)
    fire_name = Column(String)
    ics_209_incident_number = Column(String)
    ics_209_name = Column(String)
    mtbs_id = Column(String)
    mtbs_fire_name = Column(String)
    complex_name = Column(String)
    fire_year = Column(Integer)
    discovery_date = Column(String)
    discovery_doy = Column(Integer)
    discovery_time = Column(String)
    stat_cause_code = Column(String)
    stat_cause_descr = Column(String)
    cont_date = Column(String)
    cont_doy = Column(Integer)
    cont_time = Column(String)
    fire_size = Column(String)
    fire_size_class = Column(String)
    latitude = Column(String)
    longitude = Column(String)
    owner_code = Column(String)
    owner_descr = Column(String)
    state = Column(String)
    county = Column(String)
    fips_code = Column(String)
    fips_name = Column(String)
    shape = Column(Integer)